pygmentsCodeFences = false
pygmentsUseClasses = false
paginate = 9999
minify = true
disableHugoGeneratorInject = true

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
